# Generated by Django 4.0.4 on 2022-05-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('telegram_id', models.CharField(max_length=150, unique=True)),
                ('username', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('telegram_id', models.CharField(max_length=150, unique=True)),
                ('username', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('telegram_id', models.CharField(max_length=150, unique=True)),
                ('username', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Give',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('channel', models.ManyToManyField(related_name='gruxlar', to='bot_main.channel')),
                ('users', models.ManyToManyField(related_name='odamlar', to='bot_main.users')),
            ],
        ),
    ]
