# Generated by Django 4.0.4 on 2022-05-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_main', '0002_alter_give_channel_alter_give_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='give',
            name='admin',
            field=models.CharField(default='981154238', max_length=250),
            preserve_default=False,
        ),
    ]
