# Generated by Django 4.0.4 on 2022-05-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_main', '0003_give_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('telegram_id', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
